### PR TITLE
fix: Updated packages version to current ones

### PR DESCRIPTION
**Pull request by marek-knappe**
# Description

Just upgraded versions, and it looks like they are still compatible - the reason is that most of package require

### CODE REVIEW

**Review by renatosazup — DISMISSED** [review]

**Review by azhar22k — CHANGES_REQUESTED** [review]
Hey [marek-knappe](https://github.com/marek-knappe)

Thanks for contributing.
Can you please
1. Close and then reopen this PR so that the `Synk` check could finish which is currently failing.
2. use. [semantic commit](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)


I will meanwhile take some time out to review and testout the chnages

**Comment by marek-knappe** [comment]
@azhar22k  Hopefully it's ok to just amend commit message and force push - Snyk has passed :) Thanks!

**Comment by azhar22k** [comment]
I have been out for new year. Will give it a go this week

**Review by haooliveira84 — APPROVED** [review]

**Review by azhar22k — APPROVED** [review]

**Comment by azhar22k** [comment]
Now available as part of [v0.1.2](https://github.com/peak-ai/eks-token/releases/tag/v0.1.2) and [pypi as well](https://pypi.org/project/eks-token/0.1.2/)

**Pull request merged**
